apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi # Le pedimos 1 Gigabyte de disco duro

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15 # Usamos la versión compatible
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "angel_dev"
            - name: POSTGRES_PASSWORD
              value: "brasiljr08"
            - name: POSTGRES_DB
              value: "stockmaster_db"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data # Le decimos dónde "montar" el disco
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc # Le decimos qué "disco" usar

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432